// GENERATED by scripts/check-art.ts (`npm run art:check`). Do not edit by hand.
//
// The contents of the two public art buckets, so the app never has to ask at
// runtime. storage.list() is a network request; this is a string array, and
// getPublicUrl() turns a name into a URL without touching the network.
//
// Refreshed daily by the "Character art check" job in .github/workflows/
// content-checks.yml, which commits any change — so new art goes live on the
// next deploy rather than the next app launch.

/** Object names in the public `characters` bucket. */
export const CHARACTER_ART_OBJECTS: readonly string[] = [
  'abdabs_polari.png',
  'antique-hq_polari.png',
  'arva_polari.png',
  'auntie_polari.png',
  'barkey_polari.png',
  'beak_polari.png',
  'blaze-queen_polari.png',
  'boyno_polari.png',
  'bull_polari.png',
  'butch_polari.png',
  'charpering-omee_polari.png',
  'chavvy_polari.png',
  'chicken_polari.png',
  'cove_polari.png',
  'crimper_polari.png',
  'crocus_polari.png',
  'dilly_polari.png',
  'ducky_polari.png',
  'dyke_polari.png',
  'fabulosa_polari.png',
  'fish_polari.png',
  'flattie_polari.png',
  'fungus_polari.png',
  'glossy_polari.png',
  'mary_polari.png',
  'mother_polari.png',
  'nochy_polari.png',
  'palone_polari.png',
  'queen_polari.png',
  'rozzer_polari.png',
  'savvy_polari.png',
  'scarper_polari.png',
  'slap_polari.png',
  'trade_polari.png',
  'vada_polari.png',
  'vera-lynn_polari.png',
  'zhuzh_polari.png',
];

/** Object names in the public `character wallpapers` bucket. */
export const WALLPAPER_OBJECTS: readonly string[] = [
  'antique-hp_wallpaper_polari.png',
  'arva_wallpaper_polari.png',
  'auntie_wallpaper_polari.png',
  'blaze-queen_wallpaper_polari.png',
  'butch_wallpaper_polari.png',
  'charpering-omee_wallpaper_polari.png',
  'crocus_wallpaper_polari.png',
  'ducky_wallpaper_polari.png',
  'fabulosa_wallpaper_polari.png',
  'favourette_wallpaper_polari.png',
  'fish_wallpaper_polari.png',
  'fungus_wallpaper_polari.png',
  'glossy_wallpaper_polari.png',
  'mary_wallpaper_polari.png',
  'mother_wallpaper_polari.png',
  'palone_wallpaper_polari.png',
  'rozzer_wallpaper_polari.png',
  'slap_wallpaper_polari.png',
  'trade_wallpaper_polari.png',
  'vada_wallpaper_polari.png',
  'vera_wallpaper_polari.png',
  'zhuzh_wallpaper_polari.png',
];
