// GENERATED by scripts/build-privacy-policy.ts — do not edit by hand.
// Source: docs/legal/privacy-policy.md. Run `npm run legal:build` after changing it.

export type PolicySpan = { text: string; bold?: boolean; href?: string };
export type PolicyBlock =
  | { kind: 'heading'; level: 2 | 3; text: string }
  | { kind: 'paragraph'; spans: PolicySpan[] }
  | { kind: 'bullet'; spans: PolicySpan[] };

/** Shown in the card's top-right corner, straight from the document. */
export const PRIVACY_LAST_UPDATED = "13 August 2026";

export const PRIVACY_POLICY: PolicyBlock[] = [
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "This Privacy Policy explains how Polari collects, uses, stores and shares personal information when you use the Polari mobile app, website, related services and associated features."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Polari is operated by "
      },
      {
        "text": "Lorem Ipsum Creative",
        "href": "https://loremipsumcreative.com.au"
      },
      {
        "text": " (ABN 28 874 843 718), referred to in this Privacy Policy as “Polari”, “we”, “us” or “our”."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "By using Polari, you agree to the handling of your information as described in this Privacy Policy."
      }
    ]
  },
  {
    "kind": "heading",
    "level": 2,
    "text": "1. What Polari Is"
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Polari is an educational and cultural app designed to preserve, teach and celebrate Polari, the historic queer language. The app may include dictionary entries, word collections, filters, favourite words, quizzes, learning tools, illustrations and related features."
      }
    ]
  },
  {
    "kind": "heading",
    "level": 2,
    "text": "2. Information We Collect"
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "The information we collect depends on how you use Polari."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "We may collect:"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Account information, such as your email address, display name and authentication details;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "App activity, such as favourite words, viewed entries, completed quizzes, quiz scores and streaks, spaced-repetition learning progress (including how well you recall a word and when it is next due for review), collections used, filters selected and app preferences;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Your acknowledgement of the app's content advisory, recorded against your account so you are not shown it repeatedly;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Suggested corrections you submit about a dictionary entry, including the entry, the field you are correcting and the text you write. You may submit these while signed out, in which case they are not linked to an account;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Support and feedback information, such as messages you send us, the category you choose, the app version you were using and, optionally, a contact email address you give us so we can reply. You may send feedback while signed out;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Technical information, such as device type, operating system, app version, browser type, IP address, language settings and performance data."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "We do not intentionally collect sensitive information unless it is necessary for a specific feature, you choose to provide it, or we are required or authorised by law to collect it."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Because suggested corrections and feedback are free text, you may include personal or sensitive information in them even though we do not ask for it."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Please do not include personal or sensitive information in a suggested correction or feedback message - it is read and stored by us.",
        "bold": true
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "If we receive personal or sensitive information we did not solicit and could not otherwise have collected, we will delete or de-identify it as soon as practicable, unless we are required by law to keep it."
      }
    ]
  },
  {
    "kind": "heading",
    "level": 2,
    "text": "3. How We Collect Information"
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "We collect information when you:"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Create an account or sign in;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Use app features such as favourites, collections, filters, quizzes or learning progress;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Acknowledge the content advisory;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Submit a suggested correction to a dictionary entry;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Contact us for support or feedback;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Allow your device, browser or operating system to share technical information with us."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Where it is lawful and practicable, you may deal with us anonymously or under a pseudonym — for example, you can submit a suggested correction or a feedback message without signing in."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Some features, such as saving favourites, collections and learning progress, require an account and cannot be used anonymously."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Some information is collected automatically when you use Polari. See Section 6 Vercel"
      }
    ]
  },
  {
    "kind": "heading",
    "level": 2,
    "text": "4. How We Use Information"
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "We use information to:"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Provide, operate and maintain Polari;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Create and manage user accounts;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Save your preferences, favourites, collections and learning progress;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Improve app performance, reliability, accessibility and usability;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Review and act on suggested corrections to dictionary entries;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Respond to support requests, feedback or complaints;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Protect Polari, users and our systems from misuse, fraud, unauthorised access or harmful activity;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Comply with legal obligations."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "We do not sell your personal information."
      }
    ]
  },
  {
    "kind": "heading",
    "level": 2,
    "text": "5. Supabase"
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Polari uses Supabase to provide backend services, including authentication, database hosting, file storage and edge functions."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Information processed through Supabase may include your account information, authentication data, app activity, saved preferences, favourites, quiz progress, learning progress, feedback and suggested corrections."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Our Supabase project is hosted in the ap-southeast-2 (Sydney, Australia) region."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Supabase processes this information as a service provider on our behalf, subject to its own security, privacy and data-processing practices."
      }
    ]
  },
  {
    "kind": "heading",
    "level": 2,
    "text": "6. Vercel"
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Polari uses Vercel for hosting, deployment, web infrastructure and related technical services."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "When you access Polari's website or web app, Vercel may process technical information such as IP address, device information, request data, logs and performance information so the service can be delivered securely and reliably."
      }
    ]
  },
  {
    "kind": "heading",
    "level": 2,
    "text": "7. Analytics and Diagnostics"
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Polari currently uses, crash-reporting or diagnostics tools. We do not track how long you use the app, or how you move through it."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "If we add such a tool in future, we will update this Privacy Policy before switching it on, and will prefer tools that are cookieless and do not build profiles of individuals."
      }
    ]
  },
  {
    "kind": "heading",
    "level": 2,
    "text": "8. Local Storage and Cookies"
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Polari's web app stores information in your browser's local storage rather than in cookies. This is used to keep you signed in and to remember which day you last opened your word of the day."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "On mobile, the equivalent information is held in your device's secure storage."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "We do not use cookies or similar technologies for advertising, tracking or profiling."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "You can clear this information through your browser or device settings. Some features, including staying signed in, will not work if you do."
      }
    ]
  },
  {
    "kind": "heading",
    "level": 2,
    "text": "9. Push Notifications"
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Polari does not currently send push notifications, and no notification service is integrated."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "If we add them, we will ask for permission through your device first, you will be able to turn them off at any time in your device settings, and we will update this Privacy Policy."
      }
    ]
  },
  {
    "kind": "heading",
    "level": 2,
    "text": "10. How Suggested Corrections and Feedback are Reviewed"
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "When you submit a suggested correction, it is stored in our database and cannot be read back by the app or by other users."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Polari's source code is kept in a public repository, and an automated daily job writes a summary of unreviewed suggestions into that repository so we are notified of them. That summary includes the dictionary entry a suggestion relates to and a count of suggestions awaiting review. It does not include the text of your suggestion, your name, email address or account identifier, or whether you were signed in when you submitted it."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "The text of your suggestion is never published — it is only ever seen by us, when we review it. We still ask that you do not include personal or sensitive information in a suggested correction or feedback message, since it is read and stored by us. If you need to tell us something privately, use the Feedback form instead."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Feedback messages are stored in our database and are not published. They are readable only by us."
      }
    ]
  },
  {
    "kind": "heading",
    "level": 2,
    "text": "11. Sharing Information"
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "We may share information with:"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Service providers who help us operate Polari, being Supabase (backend) and Vercel (hosting);"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "GitHub, where the automated review summary described in Section 10 is stored;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Professional advisers, such as legal, accounting or technical advisers;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Authorities, regulators or law enforcement where required or authorised by law;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Another organisation if Polari is involved in a merger, acquisition, restructure, asset sale or similar transaction."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "We only share information where reasonably necessary for the purposes described in this Privacy Policy."
      }
    ]
  },
  {
    "kind": "heading",
    "level": 2,
    "text": "12. Overseas Storage and Processing"
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Our database and authentication are hosted in Australia (Sydney). Our hosting provider and code repository operate globally and may process information, including in the United States."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "By using Polari, you understand that your information may be transferred to, stored in or processed outside your country of residence."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Where required, we take reasonable steps to ensure overseas recipients handle personal information consistently with applicable privacy requirements."
      }
    ]
  },
  {
    "kind": "heading",
    "level": 2,
    "text": "13. Data Retention"
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "We keep personal information for as long as reasonably necessary to provide Polari, maintain your account, comply with legal obligations, resolve disputes, improve the app and protect our legitimate interests."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "If you delete your account, we will take reasonable steps to delete or de-identify personal information associated with it."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Suggested corrections and feedback you have submitted may be retained after your account is deleted, because they are not linked to your identity once reviewed and because they may already form part of the dictionary's editorial record."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Backup copies may remain for a limited period before being deleted in accordance with ordinary system processes."
      }
    ]
  },
  {
    "kind": "heading",
    "level": 2,
    "text": "14. Security"
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "We take reasonable steps to protect personal information from misuse, interference, loss, unauthorised access, modification and disclosure."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "These steps include row-level access controls on every table holding user information, authentication protections, encryption in transit, reputable infrastructure providers and least-privilege access practices. Feedback and suggested corrections are stored write-only: they can be submitted through the app but not read back through it."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "If a data breach occurs that is likely to result in serious harm, we will comply with our obligations under the Notifiable Data Breaches scheme, including notifying affected individuals and the Office of the Australian Information Commissioner where required."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "No method of electronic storage or transmission is completely secure. You should keep your login details confidential and use secure devices and networks."
      }
    ]
  },
  {
    "kind": "heading",
    "level": 2,
    "text": "15. Your Choices and Rights"
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Depending on where you live, you may have rights to:"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Access the personal information we hold about you;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Ask us to correct inaccurate or incomplete information;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Request deletion of your account or personal information;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Object to or restrict certain processing;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Withdraw consent where processing is based on consent;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Request a copy of certain information in a portable format;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Complain to a privacy regulator."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "To exercise these rights, contact us using the details in Section 23."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "We may need to verify your identity before responding to a request."
      }
    ]
  },
  {
    "kind": "heading",
    "level": 2,
    "text": "16. GDPR and EEA Users"
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Where the European Union General Data Protection Regulation (GDPR) applies to our processing of your personal information, Lorem Ipsum Creative is the data controller."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "We process personal information in accordance with the GDPR principles of lawfulness, fairness and transparency; purpose limitation; data minimisation; accuracy; storage limitation; integrity and confidentiality; and accountability."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Depending on the circumstances, we rely on one or more of the following lawful bases:"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Performance of a contract:",
        "bold": true
      },
      {
        "text": " where processing is necessary to provide Polari, create and manage your account, save your preferences and learning progress, or respond to a request you make;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Legitimate interests:",
        "bold": true
      },
      {
        "text": " where processing is necessary to operate, secure and improve Polari, prevent misuse, review suggested corrections, respond to feedback or protect our legal interests, provided those interests are not overridden by your rights and freedoms;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Legal obligations:",
        "bold": true
      },
      {
        "text": " where processing is necessary for us to comply with applicable law; or"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Consent:",
        "bold": true
      },
      {
        "text": " where we specifically ask for your consent. You may withdraw your consent at any time, without affecting processing carried out before withdrawal."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "If the GDPR applies to you, you may have the right to be informed about our processing; access, correct or erase your personal information; restrict or object to processing; receive certain information in a portable format; and withdraw consent where consent is the lawful basis. These rights are subject to conditions and exceptions under applicable law. Polari does not use your personal information for automated decision-making or profiling."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "To exercise a GDPR right, contact us using the details in Section 23. We will respond without undue delay and generally within one month. We may ask for information needed to verify your identity. If we cannot fulfil your request, we will explain why and tell you about available complaint and judicial-remedy options."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Personal information described in this Privacy Policy may be transferred outside the European Economic Area (EEA), including to Australia and the United States. Where the GDPR requires a transfer safeguard, we will rely on a lawful transfer mechanism, such as an adequacy decision or appropriate safeguards including the European Commission's Standard Contractual Clauses, as applicable."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "You also have the right to lodge a complaint with the data protection supervisory authority in the EEA country where you live or work, or where you believe an infringement occurred."
      }
    ]
  },
  {
    "kind": "heading",
    "level": 2,
    "text": "17. Account Deletion"
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "You can delete your account in the app: open the Account tab and choose Delete Account. You will be asked to confirm."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "You can also contact us at "
      },
      {
        "text": "hello@loremipsumcreative.com.au",
        "href": "hello@loremipsumcreative.com.au"
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "*Please note, deleting the app from your device does not delete your account or information stored in our backend systems.*"
      }
    ]
  },
  {
    "kind": "heading",
    "level": 2,
    "text": "18. Children and young people"
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Polari is not intended for anyone under 15. The app contains historical language of an explicit and adult nature, and access is restricted to people aged 15 and over, consistent with our "
      },
      {
        "text": "Terms of Use",
        "href": "https://polari-app.vercel.app/terms"
      },
      {
        "text": "."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "We do not knowingly collect personal information from anyone under that age. If we become aware that we have, we will take reasonable steps to delete it."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Before you can create an account or use Polari for the first time, we ask you to confirm that you are aged 15 or over."
      }
    ]
  },
  {
    "kind": "heading",
    "level": 2,
    "text": "19. Direct Marketing"
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "We do not send marketing communications and do not operate a mailing list."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "We may send service-related messages, such as account confirmation, password reset, security or policy updates. These are sent through our authentication provider and are necessary to operate your account."
      }
    ]
  },
  {
    "kind": "heading",
    "level": 2,
    "text": "20. Third-Party Links"
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Polari links to third-party websites, including publishers, archives and broadcasters cited as sources in the About screen."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "We are not responsible for the privacy practices or content of third-party services. You should review their privacy policies before using them."
      }
    ]
  },
  {
    "kind": "heading",
    "level": 2,
    "text": "21. Changes to this Privacy Policy"
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "We may update this Privacy Policy from time to time."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "If changes are material, we will take reasonable steps to notify you, such as through the app, website or by updating the effective date."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Your continued use of Polari after the updated Privacy Policy takes effect means you accept the updated policy."
      }
    ]
  },
  {
    "kind": "heading",
    "level": 2,
    "text": "22. Features Polari Does Not Have"
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "At the effective date above, Polari does not:"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Offer paid features, subscriptions or in-app purchases, and integrates no payment provider;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Send push notifications;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Use crash-reporting or product-analytics tools;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Use advertising or tracking cookies;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Send marketing email;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Allow file uploads of any kind;"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "Profile users or make automated decisions about them."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "We will update this Privacy Policy before any of these changes."
      }
    ]
  },
  {
    "kind": "heading",
    "level": 2,
    "text": "23. Contact Us"
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "If you have questions, requests or complaints about this Privacy Policy or how we handle personal information, contact us at:"
      }
    ]
  },
  {
    "kind": "heading",
    "level": 3,
    "text": "Lorem Ipsum Creative"
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "Australian Business Number: 28 874 843 718"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "hello@loremipsumcreative.com.au",
        "href": "hello@loremipsumcreative.com.au"
      }
    ]
  },
  {
    "kind": "bullet",
    "spans": [
      {
        "text": "+61 422 181 192",
        "href": "tel:+61422181192"
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "We will acknowledge your complaint and aim to respond within a reasonable time, generally within 30 days."
      }
    ]
  },
  {
    "kind": "paragraph",
    "spans": [
      {
        "text": "If you are in Australia and are not satisfied with our response, you may contact the "
      },
      {
        "text": "Office of the Australian Information Commissioner",
        "href": "https://www.oaic.gov.au/contact-us"
      },
      {
        "text": "."
      }
    ]
  }
];
