// Turn docs/legal/privacy-policy.md into the typed module the app renders.
//
//   npm run legal:build
//
// The Markdown is the source of truth — it is what gets reviewed, and what the
// published policy is written in. The app cannot render Markdown without a
// dependency, so this converts it once into a structure react-native can walk,
// and the result is committed. Re-run it whenever the policy changes; CI checks
// the two agree.
//
// Only the constructs the policy actually uses are supported: h2/h3, bullets,
// paragraphs, bold and links. Anything else would pass through as plain text,
// so the parser fails loudly rather than silently dropping formatting.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SOURCE = join(HERE, '../docs/legal/privacy-policy.md');
const OUT = join(HERE, '../src/content/privacyPolicy.ts');

type Span = { text: string; bold?: boolean; href?: string };
type Block =
  | { kind: 'heading'; level: 2 | 3; text: string }
  | { kind: 'paragraph'; spans: Span[] }
  | { kind: 'bullet'; spans: Span[] };

/** Split inline Markdown into spans. Handles `**bold**` and `[text](href)`. */
function parseSpans(line: string): Span[] {
  const spans: Span[] = [];
  // One pass, alternating between the two inline forms we support.
  const pattern = /\*\*(.+?)\*\*|\[([^\]]+)\]\(([^)]+)\)/g;
  let last = 0;
  let m: RegExpExecArray | null;
  while ((m = pattern.exec(line))) {
    if (m.index > last) spans.push({ text: line.slice(last, m.index) });
    if (m[1] !== undefined) spans.push({ text: m[1], bold: true });
    else spans.push({ text: m[2], href: m[3] });
    last = m.index + m[0].length;
  }
  if (last < line.length) spans.push({ text: line.slice(last) });
  return spans.filter((s) => s.text.length > 0);
}

const src = readFileSync(SOURCE, 'utf8');

// "Last updated" rides in as a raw HTML div at the top; pull the date out and
// drop the tag rather than teaching the renderer about HTML.
const updated = src.match(/Last updated:\s*([^<]+)</i);
if (!updated) throw new Error('Could not find the "Last updated" line.');
const lastUpdated = updated[1].trim();

const blocks: Block[] = [];
for (const raw of src.split('\n')) {
  const line = raw.trim();
  if (!line) continue;
  // The two stray HTML tags are layout, not content.
  if (line.startsWith('<')) continue;

  if (line.startsWith('### '))
    blocks.push({ kind: 'heading', level: 3, text: line.slice(4).trim() });
  else if (line.startsWith('## '))
    blocks.push({ kind: 'heading', level: 2, text: line.slice(3).trim() });
  else if (line.startsWith('# '))
    throw new Error(`Unexpected h1 — the screen draws the title: ${line}`);
  else if (line.startsWith('- '))
    blocks.push({ kind: 'bullet', spans: parseSpans(line.slice(2).trim()) });
  else blocks.push({ kind: 'paragraph', spans: parseSpans(line) });
}

const counts = blocks.reduce<Record<string, number>>((acc, b) => {
  acc[b.kind] = (acc[b.kind] ?? 0) + 1;
  return acc;
}, {});

const body = `// GENERATED by scripts/build-privacy-policy.ts — do not edit by hand.
// Source: docs/legal/privacy-policy.md. Run \`npm run legal:build\` after changing it.

export type PolicySpan = { text: string; bold?: boolean; href?: string };
export type PolicyBlock =
  | { kind: 'heading'; level: 2 | 3; text: string }
  | { kind: 'paragraph'; spans: PolicySpan[] }
  | { kind: 'bullet'; spans: PolicySpan[] };

/** Shown in the card's top-right corner, straight from the document. */
export const PRIVACY_LAST_UPDATED = ${JSON.stringify(lastUpdated)};

export const PRIVACY_POLICY: PolicyBlock[] = ${JSON.stringify(blocks, null, 2)};
`;

writeFileSync(OUT, body);
console.log(`  wrote ${OUT.split('/').slice(-3).join('/')}`);
console.log(`  last updated: ${lastUpdated}`);
console.log(
  `  blocks: ${Object.entries(counts)
    .map(([k, v]) => `${k}=${v}`)
    .join(', ')}`,
);
