// Report reader-suggested edits waiting to be acted on.
//
//   npm run suggestions:check
//
// Writes suggestion-changes.md describing every unresolved row, so the
// scheduled GitHub Action can commit it and you get the same notification an
// art drop or a dictionary batch gives you. This is a review log, not a queue:
// nothing is applied from it. You act on a suggestion by editing the sheet,
// then mark it resolved.
//
// Unlike the dictionary and art checks, this one NEEDS a secret. The
// suggested_edits table is write-only through the API by design — no select
// policy exists — so the anon key that those two get by with cannot read it.
// It takes the service role key, which must never be committed and is supplied
// as an Actions secret.
//
// Exit code is 0 when there is nothing waiting and 1 when there is, matching
// words:check so the workflow can branch on it the same way.

import { config } from 'dotenv';
import { createClient } from '@supabase/supabase-js';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

config({ path: '.env.local' });

const HERE = dirname(fileURLToPath(import.meta.url));
const CHANGES_PATH = join(HERE, '..', 'suggestion-changes.md');

const SUPABASE_URL =
  process.env.EXPO_PUBLIC_SUPABASE_URL ?? 'https://vduqjfwjfdwzrosztrkk.supabase.co';
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

// Sheet-facing names for the DB columns a suggestion can target, so the log
// reads in the same words as the sheet you will edit to answer it.
const FIELD_LABELS: Record<string, string> = {
  definition: 'Definition',
  example: 'In Use',
  origin: 'Origin',
  cultural_context: 'Culture',
  notes_variants: 'Notes/Variants',
  pronunciation: 'Pronunciation',
};

type Row = {
  id: string;
  field: string;
  suggestion: string;
  created_at: string;
  user_id: string | null;
  words: { term: string; slug: string } | null;
};

function render(rows: Row[]): string {
  const out: string[] = ['# Suggested edits — awaiting review', ''];
  // No generated-at stamp, for the reason check-words gives: the file must be
  // byte-stable for a given set of rows or the Action commits on every run.
  out.push('_Generated by `npm run suggestions:check`. Readers propose these from');
  out.push('the definition card; answer one by editing the sheet, then set its');
  out.push('`resolved_at`._');
  out.push('');

  if (!rows.length) {
    out.push('**Nothing waiting. ✅**');
    return out.join('\n') + '\n';
  }

  out.push(`**${rows.length} waiting.**`);
  out.push('');
  for (const r of rows) {
    const term = r.words?.term ?? '(word deleted)';
    const slug = r.words?.slug ?? '—';
    out.push(`### ${term} — ${FIELD_LABELS[r.field] ?? r.field}`);
    out.push('');
    out.push(`- **slug:** \`${slug}\``);
    out.push(`- **received:** ${r.created_at.slice(0, 10)}`);
    out.push(`- **from:** ${r.user_id ? 'a signed-in reader' : 'anonymous'}`);
    out.push(`- **suggestion:** ${r.suggestion.replace(/\n/g, ' ')}`);
    out.push('');
  }
  return out.join('\n') + '\n';
}

async function main() {
  if (!SERVICE_KEY) {
    throw new Error(
      'SUPABASE_SERVICE_ROLE_KEY is not set. suggested_edits is write-only through ' +
        'the API, so reading it needs the service role — add it to .env.local locally, ' +
        'or to the repository Actions secrets for the scheduled run.',
    );
  }
  const supabase = createClient(SUPABASE_URL, SERVICE_KEY, {
    auth: { persistSession: false },
  });

  const { data, error } = await supabase
    .from('suggested_edits')
    .select('id, field, suggestion, created_at, user_id, words(term, slug)')
    .is('resolved_at', null)
    .order('created_at', { ascending: false });
  if (error) throw error;

  const rows = (data ?? []) as unknown as Row[];
  writeFileSync(CHANGES_PATH, render(rows));

  if (!rows.length) {
    console.log('No suggested edits waiting. suggestion-changes.md is clean.');
    process.exit(0);
  }
  console.log(`${rows.length} suggested edit(s) waiting. Wrote suggestion-changes.md.`);
  process.exit(1);
}

main().catch((err) => {
  console.error(err);
  process.exit(2);
});
