// Detect Google Sheet dictionary changes and write a reviewable batch file.
//
//   npm run words:check
//
// This NEVER touches the database and needs no secrets — it only fetches the
// public sheet CSV and compares it to the last-applied snapshot
// (scripts/words-snapshot.json). It writes dictionary-changes.md describing what
// would change, then you run `npm run words:apply` when you're ready to upload.
//
// Exit code is 0 when clean and 1 when there are pending changes, so CI / the
// scheduled GitHub Action can branch on it.

import {
  fetchSheetWords,
  readSnapshot,
  writeSnapshot,
  CHANGES_PATH,
  type Diff,
  type FieldValue,
  type WordContent,
  diffWords,
} from './lib/dictionary';
import { writeFileSync } from 'node:fs';

function fmt(value: FieldValue): string {
  // "flagged" is the one boolean in the set, and this file is read by a person
  // deciding whether to upload a batch — Yes/No says more than true/false.
  if (typeof value === 'boolean') return value ? 'Yes' : 'No';
  return value === null || value === '' ? '_(empty)_' : value.replace(/\n/g, ' ');
}

function renderContent(c: WordContent): string {
  const lines = [
    `- **term:** ${fmt(c.term)}`,
    `- **type:** ${c.entry_type}`,
    `- **part of speech:** ${fmt(c.part_of_speech)}`,
    `- **pronunciation:** ${fmt(c.pronunciation)}`,
    `- **definition:** ${fmt(c.definition)}`,
    `- **origin:** ${fmt(c.origin)}`,
    `- **example:** ${fmt(c.example)}`,
    `- **notes/variants:** ${fmt(c.notes_variants)}`,
  ];
  return lines.join('\n');
}

function renderChangesFile(diff: Diff): string {
  const out: string[] = [];
  out.push('# Dictionary changes — pending upload');
  out.push('');
  // No generated-at timestamp here on purpose: the file must be byte-stable for a
  // given set of changes so the scheduled GitHub Action doesn't create a fresh
  // commit on every run. The commit date is the record of when it was detected.
  out.push('_Generated by `npm run words:check`, compared against the last applied');
  out.push('snapshot (`scripts/words-snapshot.json`)._');
  out.push('');

  if (!diff.hasChanges) {
    out.push('**No changes since the last applied snapshot. ✅**');
    out.push('');
    out.push('Nothing to upload. Edit the sheet, then run `npm run words:check` again.');
    return out.join('\n') + '\n';
  }

  out.push(
    `**Summary:** ${diff.added.length} added · ${diff.updated.length} updated · ${diff.removed.length} removed`,
  );
  out.push('');
  out.push('Run `npm run words:apply` to upload this batch to the app.');
  out.push('');

  if (diff.added.length) {
    out.push(`## ➕ Added (${diff.added.length})`);
    out.push('');
    for (const { slug, content } of diff.added) {
      out.push(`### ${content.term} — \`${slug}\``);
      out.push(renderContent(content));
      out.push('');
    }
  }

  if (diff.updated.length) {
    out.push(`## ✏️ Updated (${diff.updated.length})`);
    out.push('');
    for (const { slug, content, changes } of diff.updated) {
      out.push(`### ${content.term} — \`${slug}\``);
      for (const ch of changes) {
        out.push(`- **${ch.field.replace(/_/g, ' ')}:** ${fmt(ch.from)} → **${fmt(ch.to)}**`);
      }
      out.push('');
    }
  }

  if (diff.removed.length) {
    out.push(`## ❌ Removed (${diff.removed.length})`);
    out.push('');
    out.push('_These will be deleted from the app (and their favourites) on apply._');
    out.push('');
    for (const { slug, content } of diff.removed) {
      out.push(`### ${content.term} — \`${slug}\``);
      out.push(`- **definition:** ${fmt(content.definition)}`);
      out.push('');
    }
  }

  return out.join('\n') + '\n';
}

async function main() {
  const { words: current, optionalFields } = await fetchSheetWords();
  let snapshot = readSnapshot();

  // First run with no snapshot: establish a baseline from the current sheet and
  // report no changes. (During setup the baseline is seeded from the live DB so
  // this branch normally won't fire.)
  if (!snapshot) {
    writeSnapshot(current);
    snapshot = current;
    console.log(
      `No snapshot found — initialised baseline from the sheet (${Object.keys(current).length} words). No changes to report yet.`,
    );
  }

  const diff = diffWords(snapshot, current, optionalFields);
  writeFileSync(CHANGES_PATH, renderChangesFile(diff));

  if (!diff.hasChanges) {
    console.log('No dictionary changes. dictionary-changes.md is clean.');
    process.exit(0);
  }

  console.log(
    `Dictionary changes detected: ${diff.added.length} added, ${diff.updated.length} updated, ${diff.removed.length} removed.`,
  );
  console.log('Wrote dictionary-changes.md. Review it, then run `npm run words:apply` to upload.');
  process.exit(1);
}

main().catch((err) => {
  console.error(err);
  process.exit(2);
});
